- OCKSample.xcodeproj/project.pbxproj
- OCKSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Update ParseCareKit with fixes
> Fixed syncing of Outcomes and OutcomeValues

- OCKSample/AppDelegate.swift
- OCKSample/CareViewController.swift
- OCKSample/SceneDelegate.swift
- OCKWatchSample Extension/ExtensionDelegate.swift
Every time a sync is requested, it's displayed on the UI
> Improve synchronization

- OCKSample/AppDelegate.swift
- OCKSample/CareViewController.swift
- OCKSample/SceneDelegate.swift
- Improved console logging
- Made changes to notification name
> Fix console log comments

- OCKSample/SceneDelegate.swift
- README.md
> Always populate HealthKit store

- OCKSample.xcodeproj/project.pbxproj
- OCKSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- OCKSample/ParseObjects.swift
- OCKWatchSample Extension/ExtensionDelegate.swift
> Update ParseCareKit to fix Notes and gain OSLog

- OCKSample.xcodeproj/project.pbxproj
- OCKSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- OCKSample/AppDelegate.swift
- OCKWatchSample Extension/ExtensionDelegate.swift
Update dependencies to fix login
> Bug Fix: Login

- OCKSample.xcodeproj/project.pbxproj
- OCKSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- OCKSample/AppDelegate.swift
> Updating to latest CareStore.

- OCKSample.xcodeproj/project.pbxproj
- OCKSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- OCKSample/AppDelegate.swift
- OCKSample/Login/Login.swift
- OCKSample/MainTabs/Profile/Profile.swift
- OCKSample/SceneDelegate.swift
- OCKWatchSample Extension/ExtensionDelegate.swift
- OCKWatchSample Extension/OCKWatchSample Extension.entitlements
- README.md
Waiting for CareKit to accept bug fixes before merging.
> Update to latest CareKit Schema

- OCKSample.xcodeproj/project.pbxproj
- OCKSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- OCKSample/AppDelegate.swift
- OCKSample/MainTabs/Profile/Profile.swift
- OCKWatchSample Extension/ExtensionDelegate.swift
> Delete healthKit store on logout

- OCKSample.xcodeproj/project.pbxproj
- OCKSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- OCKSample/AppDelegate.swift
- OCKWatchSample Extension/ExtensionDelegate.swift
Update dependencies... There's a fix in ParseCareKit to prevents duplicate errors on first sync along with force sync.
> Update CareKit and ParseCareKit

- OCKSample.xcodeproj/project.pbxproj
- OCKSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> Update CareKit and ParseCareKit with OutcomeValue fixes

- OCKWatchSample Extension/ExtensionDelegate.swift
- OCKWatchSample Extension/OCKWatchSample Extension.entitlements
Updating ParseInstallation for watchOS
> Save installation for watchOS

- OCKSample.xcodeproj/project.pbxproj
- OCKSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- OCKSample/AppDelegate.swift
- OCKWatchSample Extension/ExtensionDelegate.swift
> Update to latest ParseCareKit

- OCKSample.xcodeproj/project.pbxproj
- OCKSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- OCKSample/Constants.swift
- OCKSample/Extensions/OCKPatient+Parse.swift
- OCKSample/Login/LoginView.swift
- OCKSample/Login/LoginViewModel.swift
- OCKSample/MainTabs/Profile/ProfileViewModel.swift
- OCKSample/Models/Installation.swift
- OCKSample/Models/User.swift
Update to ParseSwift 4.0.0 beta
> Parse swift update

- OCKSample.xcodeproj/project.pbxproj
- OCKSample/AppDelegate.swift
- OCKSample/Environment/StoreManagerKey.swift
- OCKSample/Login/LoginViewModel.swift
- OCKSample/MainTabs/Care/CareViewController.swift
- OCKSample/MainTabs/Profile/ProfileViewModel.swift
- OCKSample/SceneDelegate.swift
- OCKSample/WatchConnectivity/LocalSyncSessionDelegate.swift
- OCKWatchSample Extension/Care/CareViewModel.swift
More fixes, ignore the change in `OCKSample.xcodeproj/project.pbxproj`
> fix: main thread issues in Xcode 13.3

- OCKSample.xcodeproj/project.pbxproj
- OCKSample/AppDelegate.swift
- OCKSample/Constants.swift
- OCKSample/Environment/StoreManagerKey.swift
- OCKSample/Extensions/Logger.swift
- OCKSample/MainTabs/Contact/ContactView.swift
- OCKWatchSample Extension/AppDelegate.swift
- OCKWatchSample Extension/Care/CareViewModel.swift
- OCKWatchSample Extension/Environment/StoreManagerKey.swift
- README.md
> move strings to constants

- OCKSample.xcodeproj/project.pbxproj
- OCKSample/AppDelegate.swift
- OCKSample/Constants.swift
- OCKSample/Environment/CustomStylerKey.swift
- OCKSample/Environment/FontColorKey.swift
- OCKSample/Environment/StoreManagerKey.swift
- OCKSample/Environment/TintColorFlipKey.swift
- OCKSample/Environment/TintColorKey.swift
- OCKSample/Extensions/AppDelegate+ParseRemoteDelegate.swift
- OCKSample/Main/Care/CareView.swift
- OCKSample/Main/Care/CareViewController.swift
- OCKSample/Main/Contact/ContactView.swift
- OCKSample/Main/Login/LoginView.swift
- OCKSample/Main/Login/LoginViewModel.swift
- OCKSample/Main/MainTabView.swift
- OCKSample/Main/MainView.swift
- OCKSample/Main/Profile/ProfileView.swift
- OCKSample/Main/Profile/ProfileViewModel.swift
- OCKSample/Utility.swift
- OCKWatchSample Extension/Main/Care/CareView.swift
- OCKWatchSample Extension/Main/Care/CareViewModel.swift
- OCKWatchSample Extension/Main/Login/LoginView.swift
- OCKWatchSample Extension/Main/MainView.swift
> Improve previews and bug fixes

- .github/workflows/ci.yml
- .swiftlint.yml
> minor updates

- .github/workflows/ci.yml
- OCKSample.xcodeproj/project.pbxproj
- OCKSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> fix: RevisionRecord syncing with server

- OCKSample.xcodeproj/project.pbxproj
- OCKSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- OCKSample.xcodeproj/xcshareddata/xcschemes/OCKSample.xcscheme
- OCKSample.xcodeproj/xcshareddata/xcschemes/OCKWatchSample (Notification).xcscheme
- OCKSample.xcodeproj/xcshareddata/xcschemes/OCKWatchSample.xcscheme
- OCKSample/Extensions/OCKStore.swift
- OCKSample/Main/Care/CareView.swift
- OCKSample/Main/Care/CareViewController.swift
- OCKSample/Main/Login/LoginView.swift
- OCKSample/Main/Profile/ProfileView.swift
- OCKSample/Models/TaskID.swift
- OCKSample/Supporting Files/Localization/en.lproj/Localizable.strings
- OCKWatchSample Extension/Main/Care/CareView.swift
- OCKWatchSample Extension/Main/Login/LoginView.swift
- OCKWatchSample Extension/Main/MainView.swift
> feat: Improve SwiftUI and UIKit integration

- README.md
> docs: Update fork link in README

- OCKSample.xcodeproj/project.pbxproj
- OCKSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- OCKSample/Extensions/OCKHealthKitPassthroughStore.swift
- OCKSample/Extensions/OCKStore.swift
> refactor: Update dependencies and store code

- OCKSample.xcodeproj/project.pbxproj
- OCKSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- OCKSample/Extensions/OCKHealthKitPassthroughStore.swift
- OCKSample/Main/Care/CareViewController.swift
- OCKSample/Models/TaskID.swift
- OCKSample/Supporting Files/Localization/en.lproj/Localizable.strings
- OCKWatchSample Extension/Main/Care/CareView.swift
> feat: Add Support for HKCategorySamples
